# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x08registry\"S\n\x0fRegistryRequest\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x16\n\x0eserviceAddress\x18\x02 \x01(\t\x12\x13\n\x0bservicePort\x18\x03 \x01(\x05\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x10RegistryResponse\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.registry.Status2]\n\x0fRegistryService\x12J\n\x0fRegisterService\x12\x19.registry.RegistryRequest\x1a\x1a.registry.RegistryResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRYREQUEST._serialized_start=28
  _REGISTRYREQUEST._serialized_end=111
  _STATUS._serialized_start=113
  _STATUS._serialized_end=152
  _REGISTRYRESPONSE._serialized_start=154
  _REGISTRYRESPONSE._serialized_end=227
  _REGISTRYSERVICE._serialized_start=229
  _REGISTRYSERVICE._serialized_end=322
# @@protoc_insertion_point(module_scope)
